# Generated by Django 6.0.1 on 2026-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='AppartmentNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
