# Generated by Django 6.0.1 on 2026-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='PrecinctNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ZipCode',
            field=models.TextField(blank=True),
        ),
    ]
