# Generated by Django 6.0.1 on 2026-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(blank=True)),
                ('LastName', models.TextField(blank=True)),
                ('StreetNumber', models.IntegerField(blank=True)),
                ('StreetName', models.TextField(blank=True)),
                ('AppartmentNumber', models.IntegerField(blank=True)),
                ('ZipCode', models.IntegerField(blank=True)),
                ('DateOfBirth', models.DateField(blank=True)),
                ('DateOfRegistration', models.DateField(blank=True)),
                ('PartyAffiliation', models.CharField(blank=True, max_length=2)),
                ('PrecinctNumber', models.IntegerField(blank=True)),
                ('v20state', models.BooleanField(blank=True, null=True)),
                ('v21town', models.BooleanField(blank=True, null=True)),
                ('v21primary', models.BooleanField(blank=True, null=True)),
                ('v22general', models.BooleanField(blank=True, null=True)),
                ('v23town', models.BooleanField(blank=True, null=True)),
                ('voter_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
