# Generated by Django 6.0.1 on 2026-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_appartmentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='DateOfRegistration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
